### ISSUE TITLE
[ADR] Graphing and Data Display

### ISSUE THREAD

**Issue by SyniRon** [7Cav/adr#42]
## Objective
To enhance the Active Duty Roster (ADR) by adding graphing and other data display options, as well as a "recent activity" feature that tracks changes made to MILPACs.

## Key Focus Areas
1. Implement graphing and data visualization features for more intuitive data interpretation.
2. Add a "recent activity" feature to monitor recent changes in MILPACs.
3. Prepare for future integration with upcoming API improvements for further data display capabilities.

### Graphing and Data Display
1. Investigate and identify the types of graphs and data displays that would be most useful for users.
2. Implement the chosen graphs and data displays, ensuring they sort and parse data correctly.

### Recent Activity Feature
1. Design and implement a "recent activity" section that logs and displays recent changes made to MILPACs.

### Future API Integration
1. Assess current API capabilities and identify areas for improvement in anticipation of future updates.

## Problem Statement
The current ADR lacks advanced data visualization options, making it less user-friendly and informative than it could be. Additionally, there's no feature to track recent changes made to MILPACs, leaving users uninformed about recent updates.

## Future Considerations
Await further API improvements to potentially expand the data display and visualization capabilities of the ADR.

By implementing these enhancements, we aim to make the ADR more interactive, informative, and user-friendly, thereby improving the overall user experience.

**Comment by SyniRon** [comment]
Being completed by Vercin as outside collab

**Comment by Vercin-G** [comment]
Focus Area 1 complete as of most recent PR.

**Comment by SyniRon** [comment]
closing as this is stale, but partially complete

future improvements will be handled in other forums
