### ISSUE TITLE
[ADR] Refactoring

### ISSUE THREAD

**Issue by SyniRon** [7Cav/adr#49]
## Objective
To refactor the existing Active Duty Roster (ADR) codebase with the goal of adhering more closely to the DRY (Don't Repeat Yourself) principle. This will improve the code's readability and maintainability.

## Key Focus Areas
1. Code Duplication: Identify and eliminate redundant code blocks.
2. Code Structure: Reorganize the code to make it more intuitive and easier to follow.
3. Documentation: Add comments and documentation to clarify the purpose and functionality of different code sections.

### Code Duplication
1. Conduct a thorough review of the existing ADR code to identify instances of code duplication.
2. Abstract duplicated code into reusable functions or modules.

### Code Structure
1. Reorganize the code structure, considering aspects like function order, module organization, and data flow.
2. Implement best practices such as meaningful variable names, consistent indentation, and modular design.

### Documentation
1. Add inline comments to complex or unintuitive code sections.
2. Update or create documentation outlining the code structure, functions, and flow to assist future developers.

## Problem Statement
The current ADR codebase contains redundant code and lacks a structure that is easy to understand and maintain.

## Optional Features
1. Implement automated tests to ensure that the refactoring has not introduced any bugs.
2. Conduct a peer code review to validate the quality and effectiveness of the refactoring.

By refactoring the ADR code, we aim to create a more efficient, readable, and maintainable codebase, which will facilitate easier updates and debugging in the future.

**Comment by Vercin-G** [comment]
Majority of bloat in app.js consolidated in PR #51. Could possibly be reduced even further with further improvement to how MilpacParse.js intakes objects. But doing so may further complicate an already complex ArrayMap.js.

Vast majority of structure issues addressed in PR #54. Now, BilletBank.js entirely defines all Milpac.js input items, and exports said items in a neatly tied up single object. Additionally, CombinedFunction.js has been split into its individual functions. Documentation has been added to said functions. 

Upcoming iterations of the ADR will likely include routing, in which the statistics section is remade and moved to its seperate page entirely. 

I think this ticket can be marked as complete, unless Sypolt has further objection.
