### ISSUE TITLE
React.js --> Next.js Refactor

### ISSUE THREAD

**Issue by Vercin-G** [7Cav/adr#58]
Once PR #57 becomes live, a fundamental rebuild of CavApps in Next.JS will be an eventual requirement.

This is due to the following reasons:

* As the JavaScript count increases, react will download every javascript file for every page in CavApps, even if certain pages are never opened by the end user.
* Severside rendering will allow us to eliminate the API call on the clientside. Thus removing the requirement to download an additional 10mb of data on the clientside. 
* The CSS styling for CavApps is starting to become cluttered and intuitive.  While manual styling may suit us for some time, Next.js' native support of external CSS tools may serve useful if others start developing in CavApps.
* CavApps was originally built as a single page ADR project. However, should we wish to expand to more serious development. i.e. utilizing authentication elements such as keycloak for multiple apps. It may be useful to update to a framework which allows us extra security.

**Comment by mirislomovmirjalol** [comment]
As the JavaScript count increases, react will download every javascript file for every page in CavApps, even if certain pages are never opened by the end user. Next.JS uses server-side rendering, which would eliminate the need to download all of the JavaScript files for every page.

Server-side rendering would also allow us to eliminate the API call on the clientside, which would remove the requirement to download an additional 10MB of data.

The CSS styling for CavApps is starting to become cluttered and intuitive. While manual styling may suit us for some time, Next.js' native support of external CSS tools may serve useful if others start developing in CavApps.

CavApps was originally built as a single page ADR project. However, should we wish to expand to more serious development, i.e. utilizing authentication elements such as keycloak for multiple apps, it may be useful to update to a framework which allows us extra security. Next.JS offers a number of security features, such as built-in support for authentication and authorization.

**Comment by Vercin-G** [comment]
As of now, the code for the migration is complete enough to warrant a staging build and deployment. once i can iron out the staging build on a live setting, i can finish off work on the migration.

see here for the current nextJS version: https://github.com/Vercin-G/adr/tree/nextjs-dev

**Comment by SyniRon** [comment]
closing as this was done in #70
